services:
  db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: unless-stopped
    env_file: .env
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '${SA_PASSWORD:-secret_password}'
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
